import Constants from 'expo-constants'

interface IEnvironment {
  APP_VARIANT: string
  API_URL: string
  AUTHENTICATION_KEY: string
  AUTHENTICATION_USER_KEY: string
  THEME_STORAGE_KEY: string
  EAS_PROJECT_ID: string
  EAS_PREVIEW_URL: string
  IOS_BUNDLE_IDENTIFIER: string
  ANDROID_PACKAGE_NAME: string
}

const {
  APP_VARIANT,
  API_URL,
  AUTHENTICATION_KEY,
  AUTHENTICATION_USER_KEY,
  THEME_STORAGE_KEY,
  EAS_PROJECT_ID,
  EAS_PREVIEW_URL,
  IOS_BUNDLE_IDENTIFIER,
  ANDROID_PACKAGE_NAME
} = Constants.expoConfig?.extra as IEnvironment

const environment = {
  APP_VARIANT: APP_VARIANT || 'NOT ASSIGNED',
  API_URL: API_URL || 'NOT ASSIGNED',
  AUTHENTICATION_KEY: AUTHENTICATION_KEY || 'NOT ASSIGNED',
  AUTHENTICATION_USER_KEY: AUTHENTICATION_USER_KEY || 'NOT ASSIGNED',
  THEME_STORAGE_KEY: THEME_STORAGE_KEY || 'NOT ASSIGNED',
  EAS_PROJECT_ID: EAS_PROJECT_ID || 'NOT ASSIGNED',
  EAS_PREVIEW_URL: EAS_PREVIEW_URL || 'NOT ASSIGNED',
  IOS_BUNDLE_IDENTIFIER: IOS_BUNDLE_IDENTIFIER || 'NOT ASSIGNED',
  ANDROID_PACKAGE_NAME: ANDROID_PACKAGE_NAME || 'NOT ASSIGNED'
}

// const environment = developmentEnvironment // Constants.expoConfig?.extra?.env === 'preview' ? previewEnvironment : developmentEnvironment

export { environment }
