import Constants from 'expo-constants'
interface IEnvironment {
  APP_VARIANT: string
  SAE_EMPLOYEEAPP_API_URL: string
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY: string
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY: string
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY: string
}

const {
  APP_VARIANT,
  SAE_EMPLOYEEAPP_API_URL,
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY,
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY,
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY
} = Constants.expoConfig?.extra as IEnvironment

const environment = {
  APP_VARIANT: APP_VARIANT || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_API_URL: SAE_EMPLOYEEAPP_API_URL || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_AUTHENTICATION_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_KEY || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY: SAE_EMPLOYEEAPP_AUTHENTICATION_USER_KEY || 'NOT ASSIGNED',
  SAE_EMPLOYEEAPP_THEME_STORAGE_KEY: SAE_EMPLOYEEAPP_THEME_STORAGE_KEY || 'NOT ASSIGNED'
}

// const environment = developmentEnvironment // Constants.expoConfig?.extra?.env === 'preview' ? previewEnvironment : developmentEnvironment

export { environment }
