import Constants from 'expo-constants'
import {
  APP_VARIANT as ENV_APP_VARIANT,
  API_URL as ENV_API_URL,
  AUTHENTICATION_KEY as ENV_AUTHENTICATION_KEY,
  AUTHENTICATION_USER_KEY as ENV_AUTHENTICATION_USER_KEY,
  THEME_STORAGE_KEY as ENV_THEME_STORAGE_KEY
} from '@env'

interface IEnvironment {
  APP_VARIANT: string
  API_URL: string
  AUTHENTICATION_KEY: string
  AUTHENTICATION_USER_KEY: string
  THEME_STORAGE_KEY: string
  EAS_PROJECT_ID: string
  EAS_PREVIEW_URL: string
  IOS_BUNDLE_IDENTIFIER: string
  ANDROID_PACKAGE_NAME: string
}

// Obtener variables de expo-constants (funciona en builds nativos)
const expoExtra = Constants.expoConfig?.extra as IEnvironment | undefined

const environment: IEnvironment = {
  APP_VARIANT: ENV_APP_VARIANT || expoExtra?.APP_VARIANT || 'NOT ASSIGNED',
  API_URL: ENV_API_URL || expoExtra?.API_URL || 'NOT ASSIGNED',
  AUTHENTICATION_KEY: ENV_AUTHENTICATION_KEY || expoExtra?.AUTHENTICATION_KEY || 'NOT ASSIGNED',
  AUTHENTICATION_USER_KEY: ENV_AUTHENTICATION_USER_KEY || expoExtra?.AUTHENTICATION_USER_KEY || 'NOT ASSIGNED',
  THEME_STORAGE_KEY: ENV_THEME_STORAGE_KEY || expoExtra?.THEME_STORAGE_KEY || 'NOT ASSIGNED',
  EAS_PROJECT_ID: expoExtra?.EAS_PROJECT_ID || 'NOT ASSIGNED',
  EAS_PREVIEW_URL: expoExtra?.EAS_PREVIEW_URL || 'NOT ASSIGNED',
  IOS_BUNDLE_IDENTIFIER: expoExtra?.IOS_BUNDLE_IDENTIFIER || 'NOT ASSIGNED',
  ANDROID_PACKAGE_NAME: expoExtra?.ANDROID_PACKAGE_NAME || 'NOT ASSIGNED'
}

export { environment }
